### PR TITLE
Fix "source" name issues for `product_store`

### LINKED ISSUE #120: Creator name printed via spdlog is malformed
There is likely a memory overwrite/data race occurring that prevents a reasonable printout of the creator name.  For example, in the following terminal printout, the characters following "`source:`" should be the name of the creator.  Most of the time, this value is either empty or malformed, likely indicating accessing stale memory.

```console
⋮
[2025-11-17 17:02:35.946] [debug] [run:0]: 3 @ Mon Nov 17 17:02:35 2025
[2025-11-17 17:02:35.946] [debug] Saving data for store id: 0x60000374c000 from source: 
 -> Product name: number
[2025-11-17 17:02:35.946] [debug] Saving data for store id: 0x60000374c000 from source: 
 -> Product name: squared_number
[2025-11-17 17:02:35.946] [debug] Saving data for store id: 0x6000037540c0 from source: 
 -> Product name: number
[2025-11-17 17:02:35.946] [debug] Saving data for store id: 0x6000037540c0 from source: 
 -> Product name: squared_number
[2025-11-17 17:02:35.946] [debug] Saving data for store id: 0x60000375c0c0 from source: 
 -> Product name: number
[2025-11-17 17:02:35.946] [debug] Saving data for store id: 0x60000375c0c0 from source: p`
 -> Product name: squared_number
[2025-11-17 17:02:35.946] [debug] Saving data for store id: 0x60000375c120 from source: 
 -> Product name: number
[2025-11-17 17:02:35.946] [debug] Saving data for store id: 0x60000375c120 from source: `
 -> Product name: squared_number
[2025-11-17 17:02:35.946] [debug] [run:1]: 3.7416573867739413 @ Mon Nov 17 17:02:35 2025
[2025-11-17 17:02:35.946] [debug] Saving data for store id: 0x60000375c000 from source: 
 -> Product name: added_data
[2025-11-17 17:02:35.946] [debug] Saving data for store id: 0x60000375c000 from source: 6?
 -> Product name: result
[2025-11-17 17:02:35.946] [debug] Routed 26 messages in 59 microseconds (2.269 microseconds per message)
[2025-11-17 17:02:35.946] [info] 
Processed levels:

  job
   │ 
   └ run: 2
      │ 
      └ event: 10
```

### PR DESCRIPTION
**Pull request by greenc-FNAL**
Fixes #120.

#120 reported that diagnostic output in tests was empty or malformed.

1. The malformed output was due to `product_store` saving a `string_view` to a temporary string provided at construction time.
1. The empty output had two different causes:

   1. The `base()` product store was not initialized with a name.
   1. At least one test (`hierarchical_nodes`) creates child product stores without providing a name.

- Problem 1 is fixed by ensuring that `string`s are passed and saved rather than `string_views`.
- Problem 2.1 is fixed by allowing the `static` member function `product_store::base()` to accept an optional `base_name`, which defaults to "Source" if not provided.
- Problem 2.2 is fixed by passing a name ("levels_to_process") to the function calls creating child product stores.

There remains a question of whether `product_store::make_child()` should:

1. Continue to allow for no name specification
1. Require a name specification
1. Provide a default

### CODE REVIEW

File: phlex/model/product_store.hpp [hunk 1]
```diff
@@ -60,24 +60,24 @@ namespace phlex::experimental {
...
                            std::string const& new_level_name,
-                           std::string_view source,
+                           std::string source,
                            stage processing_stage);
 
     product_store_const_ptr parent_{nullptr};
     products products_{};
     level_id_ptr id_;
-    std::string_view source_;
+    std::string source_;
```
Comment (knoepfel) [inline phlex/model/product_store.hpp]:
```suggestion
    std::string source_;  // FIXME: Should not have to copy the string (the source should outlive the product store)
```

File: .devcontainer/devcontainer.json [hunk 2]
```diff
@@ -0,0 +1,73 @@
+{
```
Comment (knoepfel) [inline .devcontainer/devcontainer.json]: Can we include this file as part of a separate PR?

**Review by knoepfel — COMMENTED** [review]
Thanks, @greenc-FNAL, for the PR.  Just a few comments below.
